window.CVP_LEGAL_CONFIG = {
  companyName: "CV PRO BAT SOLUTION",
  commercialName: "CV PRO BAT SOLUTION",
  legalForm: "SASU, société par actions simplifiée unipersonnelle",
  capital: "1 000,00 €",
  siren: "941 975 765",
  siret: "941 975 765 00012",
  rcs: "941 975 765 R.C.S. Evry",
  vatNumber: "FR20941975765",
  apeCode: "71.12B — Ingénierie, études techniques",
  registeredOffice: "2 avenue de Villeneuve, 91940 Gometz-le-Châtel",
  publicationDirector: "Vivien Cazaux Vallée",
  president: "Vivien Cazaux Vallée",
  email: "cvprobatsolution@outlook.fr",
  phone: "07 85 91 62 63",
  website: "www.cvprobatsolution.fr",
  hostingMode: "Auto-hébergement par l'éditeur via infrastructure personnelle sécurisée",
  technicalProvider: "Cloudflare France SAS",
  technicalProviderAddress: "6 place de la Madeleine, 75008 Paris",
};
